#ifndef CASHIER_H
#define CASHIER_H
#include <fstream>
using namespace std;
#include <ctime>
#include <string>

typedef fstream fileHandler;

class CASHIER
{
private:
    
public:
/**
 * @brief Constructor for the CASHIER class.
 * @param args Additional arguments (if any would be added by another developer).
 */
    CASHIER(/* args */);
    /**
 * @brief Destructor for the CASHIER class.
 */
    ~CASHIER();

    /**
 * @brief Write cashier statistics to a file.
 * @param totalItemsbought The total number of items bought.
 * @param grossRev The gross revenue generated by the cashier.
 */
    static void writeStat(int totalItemsbought, int grossRev);
};

#endif
